dist: xenial
language: python
python:
  - '3.7'
stages:
  - build
  - static-checks
  - test
jobs:
  include:
    - stage: build
      script:
        - python setup.py install
    - stage: static-checks
      script:
        - flake8 maruval/ tests/ setup.py
        - mypy maruval/ tests/ setup.py
        - black --check .
        - isort -m 3 -tc -c maruval/* tests/* setup.py
    - stage: test
      script:  # coverage
        - coverage run -m unittest
        - coverage report
        - codecov
